name: tinatasks
description: Flutter app for Vikunja

version: 0.1.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.24.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  after_layout: ^1.2.0
  intl: ^0.19.0
  flutter_local_notifications: ^17.0.0
  rxdart: ^0.27.7
  flutter_timezone: ^1.0.8
  flutter_secure_storage: ^9.0.0
  datetime_picker_formfield: ^2.0.1
  flutter_typeahead: ^5.2.0
  build: ^2.4.1
  petitparser: ^6.0.2
  flutter_colorpicker: ^1.1.0
  flutter_keyboard_visibility: ^6.0.0
  dotted_border: ^2.1.0
  url_launcher: ^6.2.5
  workmanager: ^0.5.2
  permission_handler: ^11.3.0
  dynamic_color: ^1.7.0
  flutter_widget_from_html: ^0.14.11
  flutter_downloader: ^1.11.6
  meta: ^1.15.0
  timezone: ^0.9.2
  json_annotation: ^4.8.1
  collection: ^1.18.0
  cupertino_http: ^1.4.0
  cronet_http: ^1.2.0
  package_info_plus: ^4.2.0
  html_editor_enhanced: ^2.6.0
  # Code Helpers
  fpdart: ^1.1.1
  provider: ^6.1.2
  # Theme and Style
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
    version: any
  test: ^1.24.9
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/llama_circle.png"
  image_path_ios: "assets/icons/llama_square.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/llama_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/llama.svg
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand-v7-latin-regular.ttf
